
class Items {

  static List<String> items = [
    "Asparagus","Beets","Cauliflower","Carrots","Celery","Corn","Cucumbers","Greens","Lettuce","Mushrooms","Onions","Peppers","Potatoes","Spinach","Sprouts","Squash","Tomatoes","Zucchini",
    "Apples","Avocado","Bananas","Berries","Cherries","Grapes","Kiwis","Limes","Melons","Oranges","Peaches","Pears","Plums","Applesauce","Baked beans","Beans","Carrots","Corn",
    "Beans","Mixed fruit","Mixed veggies","Olives","Pasta sauce","Pickles","Refried beans","Tuna,Soups","Tomatoes",
    "BBQ sauce","Hot sauce","Salsa","Soy sauce","Steak sauce","Syrup","Worcestershire sauce",
    "Bottled water","Bullion cubes","Cereal","Coffee","Gravy","Honey","Jelly","Ketchup","Lime juice","Mac & cheese","Mayonnaise","Mustard",
    "Waffle mix","Peanut butter","Ramen","Soda pop","Tea","White","Wild rice",
    "Basil","Black pepper","Cilantro","Cinnamon","Garlic","Oregano","Parsley","Red pepper","Salt","Vanilla extract",
    "Oils/Vinegars","Apple cider vinegar","Balsamic vinegar","Salad dressing","Olive  oil","Vegetable oil","White",
    "Chip dip","Eggs","Juice","Ready-bake breads","Tofu,Tortillas",
    "Butter","Half & half","Heavy cream","Margarine","Milk","Sour cream","Whipped cream","Yogurt",
    "Cheddar","Cottage cheese","Cream cheese","Feta","Mozzarella","Parmesan","Pepper","Provolone","Ricotta","Sandwich slices","Shredded","Swiss",
    "Burittos","Desserts","Fish sticks","Ice cream","Juices","Pizzas","Popsicles","Fries","Sorbet",
    "TV dinners","Vegetables","Veggie burgers",
    "Bacon","Beef","Chicken","Ground beef","Ground turkey","Ham","Hot dogs","Lunchmeat","Pork","Sausage",
    "Steak","Turkey",
    "Catfish","Cocktail sauce","Crab","Halibut","Oysters","Salmon","Shrimp","Tilapia","Tuna",
    "Bagels","Buns","Cake","Cookies","Crackers","Croissants","Donuts","Fresh bread","Pastries",
    "Pie","Pitas","Rolls",
    "Sliced bread",
    "Baking powder","Baking soda","Bread crumbs","Brown sugar","Cake decorations","Cake icing",
    "Brownie mix","Chocolate chips","Cocoa","Flour","Oatmeal","Pie shell",
    "Powdered sugar","Shortening","Sugar","Yeast","Candy","Cookies","Dried fruit","Granola bars","Gum",
    "Nuts","Popcorn","Potato chips","Pudding","Pretzels","Tortilla chips",
    "Antiperspirant","Bath soap","Conditioner","Condoms","Cosmetics","Deodorant","Facial cleanser",
    "Facial tissue","Floss",
    "Hair gel","Hand soap","Lip balm","Moisturizing lotion","Mouthwash","Q-Tips","Razors","Shampoo","Shaving cream",
    "Toilet paper","Toothpaste",
    "Allergy","Antidiarrheal","Aspirin","Antacid","Band-aids","Cold","Feminine products","Prescription","Sinus",
    "Vitamins",
    "Aluminum foil","Coffee filters","Dish  soap","Dishwasher soap","Disposable cups","Disposable cutlery",
    "Disposable plates","Freezer bags","Napkins",
    "Non-stick spray","Paper towels","Plastic wrap","Roasting pan","Sandwich bags","Sponges","Wax paper",
    "Air freshener","Bathroom cleaner","Bleach","Dryer sheets","Fabric softener","Floor cleaner","Garbage bags",
    "Glass cleaner","Laundry detergent","Mop head","Spray polish","Vacuum bags",
    "Automotive","Batteries","Candles","CDRs","Charcoal","Fresh flowers","Greeting cards","Hardware",
    "Insect repellent","Insecticides","Light bulbs","Magazine","Newspaper",
    "Random impulse buy","Sunscreen",
    "Cat food","Cat litter","Cat treats","Dog food","Dog treats","Flea treatment","Pet shampoo",
    "Baby food","Bottles","Diaper lotion","Formula,Wipes",
    "supplies","Envelopes","Glue","Notepads","Paper","Pens","Pencils","Scotch tape",
    "Beer","Champagne","Club soda","Gin",
    "Malt beverage","Red wine","Rum",
    "Sake","Tonic","Whiskey","White wine","Vodka",
    "Burger night","Chili night","Pizza night","Spaghetti night","Taco night",
  ];

  userAsStringByName() {}
}